stages:
  - install_deps
  - push
  - run
  - clean

install_deps:
  stage: install_deps
  script:
    - /usr/local/maven/apache-maven-5.3.3/bin/mvn clean package
    - cp target/myshop-service-user-provider-$APP_VERSION.jar docker
    - cd docker
    - docker build -t myshop-service-user-provider:v1.0.0 .


push:
  stage: push
  script:
    - docker push 192.....:5000/myshop-service-user-provider:v1.0.0


run:
  stage: run
  script:
    - cd docker
    - docker-compose down
    - docker-compose up -d

clean:
  stage: clean
  script:
    - docker rmi $(docker images -q -f dangling=true)
